spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasty-restaurants
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

api:
  security:
    token:
      secret: dev-secret
      expiration: 3600000
